language: node_js
cache:
  directories:
    - node_modules # Speed up npm install
node_js:
  - "5.10.1"
  - "6.3.1"
  - "7.9.0"
  - "8.11.3"
  - "9.9.0"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_script:
  - npm install -g gulpjs/gulp#4.0
  - cd project
  - npm install
script: gulp build_dist
